pipeline {
    agent any
    
    environment {
        ACR_NAME   = 'clickarenaregistry'
        ACR_LOGIN  = "${ACR_NAME}.azurecr.io"
        IMAGE_NAME = 'click-arena'
        RG         = 'click-arena-rg'
        APP_NAME   = 'click-arena'
        IMAGE_TAG  = "v${BUILD_NUMBER}"
    }
    
    stages {

        stage('Checkout') {
            steps {
                echo '--- Retrieving GitHub Code ---'
                checkout scm
            }
        }

        stage('SAST — SonarQube') {
            steps {
                echo '--- Static code analysis ---'
                withCredentials([
                    string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')
                ]) {
                    sh '''
                        sonar-scanner \
                            -Dsonar.projectKey=click-arena \
                            -Dsonar.sources=./app \
                            -Dsonar.host.url=http://host.docker.internal:9000 \
                            -Dsonar.login=$SONAR_TOKEN \
                            -Dsonar.python.version=3 \
                            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc
                    '''
                }
            }
        }


        stage('SCA — Snyk') {
            steps {
                echo '--- Dependency vulnerability scan ---'
                withCredentials([
                    string(credentialsId: 'SNYK_TOKEN', variable: 'SNYK_TOKEN')
                ]) {
                    sh '''
                        cd app
                        pip3 install -r requirements.txt --quiet
                        snyk auth $SNYK_TOKEN
                        snyk test --file=requirements.txt \
                            --package-manager=pip \
                            --command=python3 \
                            --skip-unresolved \
                            --severity-threshold=high \
                            || true
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                echo '--- Building Docker Image ---'
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Push to ACR') {
            steps {
                echo '--- Pushing to Azure Container Registry ---'
                withCredentials([
                    string(credentialsId: 'ACR_PASSWORD', variable: 'PASS'),
                    string(credentialsId: 'ACR_USERNAME', variable: 'USER')
                ]) {
                    sh '''
                        echo $PASS | docker login ${ACR_LOGIN} --username $USER --password-stdin
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ACR_LOGIN}/${IMAGE_NAME}:${IMAGE_TAG}
                        docker push ${ACR_LOGIN}/${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy to Container App') {
            steps {
                echo '--- Deploying to Azure Container App ---'
                withCredentials([
                    string(credentialsId: 'AZURE_CREDENTIALS', variable: 'AZ_CREDS')
                ]) {
                    sh '''
                        CLIENT_ID=$(echo $AZ_CREDS | python3 -c "import sys,json; print(json.load(sys.stdin)['clientId'])")
                        CLIENT_SECRET=$(echo $AZ_CREDS | python3 -c "import sys,json; print(json.load(sys.stdin)['clientSecret'])")
                        TENANT_ID=$(echo $AZ_CREDS | python3 -c "import sys,json; print(json.load(sys.stdin)['tenantId'])")

                        az login --service-principal \
                            --username $CLIENT_ID \
                            --password $CLIENT_SECRET \
                            --tenant $TENANT_ID

                        az containerapp update \
                            --name click-arena \
                            --resource-group click-arena-rg \
                            --image clickarenaregistry.azurecr.io/click-arena:v5
                    '''
                }
            }
        }


        stage('Ansible - Post Deployement Verification') {
            steps {
                sh 'ansible-playbook ansible/playbook.yml'
            }
        }


        
        stage('Smoke Test') {
            steps {
                echo '--- Confirming app is alive ---'
                sh '''
                    sleep 15
                    curl -f https://click-arena.mangobush-de01fc2e.eastus.azurecontainerapps.io/health
                '''
            }
        }

    }

    post {
        success { echo 'Pipeline complete — game is live' }
        failure { echo 'Pipeline failed — check logs above' }
        always  { sh 'docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true' }
    }
}